export let database = [
  {
    id: 1,
    name: "Iqboljon Yuldashev",
    year: 2002,
    status: "student",
		isPaid: true,
    isEdited: false,
  },
  {
    id: 2,
    name: "Asilbek Tolipov",
    year: 2000,
    status: "student",
		isPaid: true,
    isEdited: false,
  },
  {
    id: 3,
    name: "Najmiddin Nazarov",
    year: 2002,
    status: "student",
		isPaid: true,
    isEdited: false,
  },
  {
    id: 4,
    name: "Mominov Abdulloh",
    year: 2002,
    status: "student",
		isPaid: true,
    isEdited: false,
  },
  {
    id: 5,
    name: "Sardor Tursunboyev",
    year: 1995,
    status: "student",
		isPaid: true,
    isEdited: false,
  },
  {
    id: 6,
    name: "Hudoyberdieva Mohichehra",
    year: 2002,
    status: "student",
		isPaid: true,
    isEdited: false,
  },
  {
    id: 7,
    name: "Muhammad Nurmirzayev",
    year: 2007,
    status: "student",
		isPaid: true,
    isEdited: false,
  },
  {
    id: 8,
    name: "Shukurov Shohruh",
    year: 2002,
    status: "student",
		isPaid: true,
    isEdited: false,
  },
];
